config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders
  resources :products, :charges

  # Resource routes for the messaging feature using mailboxer
  resources :conversations do
    resources :messages
  end

  devise_for :users

  # route for user products
  get 'products/userproducts/:user_id/' => 'products#userproducts', :as => :userproducts
  get 'products/admin_index/admin' => 'products#admin_index', :as => :admin_index
  get 'orders/myorders/:buyer_id' => 'orders#myorders', :as => :myorders
  get 'orders/mysales/:seller_id' => 'orders#mysales', :as => :mysales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # route for delete conversation
  delete 'conversations/:id/' => 'conversations#destroy', :as => :conversation_destroy

  # Root path = products index
  root 'products#index'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def index
        # byebug
        @conversations = current_user.mailbox.conversations
    end

    def show
        @conversation = current_user.mailbox.conversations.find(params[:id])
    end

    def new
        # params variable 'r' is the recipient user id
        @recipient = User.find(params[:r])   
    end

    def create
        recipient = User.find(params[:recipient_id])
        receipt = current_user.send_message(recipient, params[:body], params[:subject])
        redirect_to conversation_path(receipt.conversation)
    end

    def destroy
        @conversation = current_user.mailbox.conversations.find(params[:id])
        @conversation.destroy
        respond_to do |format|
            format.html { redirect_to conversations_path, notice: 'Product was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<h1>Inbox</h1>
<table>
    <thead>
        <tr>
            <th>Subject</th>
            <th>Received</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% for conversation in @conversations do %>
            <tr>
                <td><strong><%= link_to conversation.subject, conversation_path(conversation) %></strong></td>
                <td><%= time_ago_in_words(conversation.created_at) %> ago</td>
                <td><%= link_to 'Delete', conversation_destroy_path(conversation), method: :delete, data: { confirm: 'Are you sure?' } %></td>                
            </tr>
        <% end %>
    <tbody>
<table>
<%= link_to 'Back to shopping', products_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
    <div>
        <%= "Send a message to #{@recipient.username}" %>
    </div>
    
    <%= hidden_field_tag :recipient_id, @recipient.id %>

    <div class="field">
        <%= text_field_tag :subject, nil, placeholder: 'Subject' %>
    </div>

    <div class="field">
        <%= text_area_tag :body, nil, placeholder: "Send a message" %>
    </div>  

    <div class="actions">
        <%= submit_tag 'Send' %>
    </div>
<% end %> 

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %> </h1>

<% for receipt in @conversation.receipts_for(current_user) %>
    <div>
        <table>
            <tbody>
                <tr>
                    <td><strong><%= receipt.message.sender.username == current_user.username ? "You commented:" : "#{receipt.message.sender.username} commented:" %></strong></td>
                </tr>
                <tr>
                    <td><strong>On:</strong> <%= time_tag(receipt.message.created_at) %></td>
                </tr>
                <tr>
                    <td><strong>With:</strong> <%= receipt.message.body %></td>
                </tr>
            </tbody>
        </table>
    </div>
    <br/>
<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
    <div class="field">
        <%= label_tag :body, 'Continue conversation:' %>
        <%= text_area_tag :body %>
    </div>

    <div class="actions">
    <%= submit_tag 'Send' %>
    </div>
<% end %>

<%= link_to 'Back to Inbox', conversations_path %> | <%= link_to 'Back to shopping', products_path %>