config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders
  resources :products, :charges

  # Resource routes for the messaging feature using mailboxer
  resources :conversations do
    resources :messages
  end

  devise_for :users

  # route for user products
  get 'products/userproducts/:user_id/' => 'products#userproducts', :as => :userproducts
  get 'products/admin_index/admin' => 'products#admin_index', :as => :admin_index
  get 'orders/myorders/:buyer_id' => 'orders#myorders', :as => :myorders
  get 'orders/mysales/:seller_id' => 'orders#mysales', :as => :mysales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # route for delete conversation
  delete 'conversations/:id/' => 'conversations#destroy', :as => :conversation_destroy

  # Root path = products index
  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  
  has_one_attached :image
  
  
  # adds validation and sanitization to fields of product form when creating and updating a product
  validates :product_title, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {minimum: 10}
  validates :price, presence: true, numericality: true
  validates :medium, presence: true, length: {maximum: 25}
  validates :quantity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :creator, presence: true, length: {maximum: 50}
  
  ## image validation using the activestorage-validator gem
  # validates :image, presence: {message: 'required'}, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'] }
  
  validate :image_attached?
  
  # validates if a user has authorisation to make changes
  def can_change?(user)
    self.user == user || user.has_role?(:admin)
  end
  
  
  # converts price into cents for stripe
  def price_in_cents
    (price * 100).to_i
  end
  
  # custom image validation
  def image_attached?
    if !image.attached?
      errors.add(:image, 'required')
    elsif !image.blob.content_type.start_with?('image/', 'img/')
      errors.add(:image, 'image mustr be of type JPG or PNG')
    end
  end
  
  # quantity validation if zero
  def quantity_zero?
    self.quantity == 0 
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :check_permissions, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]
  
  # GET /products
  # GET /products.json
  
  def index
    # index for available products
    @availableproducts = Product.where.not(:quantity => 0)
  end
  
  #admin index only for admin
  def admin_index
    if current_user.has_role?(:admin)
      @products = Product.all
    else
      redirect_to products_path
    end
  end
  
  
  # for user products
  def userproducts
    @user = User.find(params[:user_id])
    @userproducts = @user.products.where.not(:quantity => 0)
  end
  
  
  
  # GET /products/1
  # GET /products/1.json
  def show
    session[:product_id] = params[:id]
  end
  
  # GET /products/new
  def new
    @product = Product.new
  end
  
  # GET /products/1/edit
  def edit
  end
  
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.image.attach(product_params[:image]) 
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
  
  # verify current user had permission to make changes; if not redirects to referer path and alert
  def check_permissions
    unless @product.can_change?(current_user)
      redirect_to(request.referer || root_path)
      flash[:alert] = "You are not authorised to perform that action!"
    end
  end
  
  def product_params
    params.require(:product).permit(:product_title, :description, :price, :medium, :quantity, :creator, :user_id, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container-fluid">
        <div class="jumbotron">
          <strong>What are you selling?</strong>
        </div>
          <div class="jumbotron">
            <div class="field">
              <%= form.label :product_title %>
            <div class="container"><%= form.text_field :product_title %></div>
          </div>

          <div class="field">
            <%= form.label :description %>
            <div class="container"><%= form.text_area :description %></div>
          </div>

          <div class="field">
            <%= form.label :price %>
            <div class="container"><%= form.text_field :price %></div>
          </div>

          <div class="field">
            <%= form.label :medium %>
            <div class="container"><%= form.text_field :medium %></div>
          </div>

          <div class="field">
            <%= form.label :quantity %>
            <div class="container"><%= form.text_field :quantity %></div>
          </div>

          <div class="field">
            <%= form.label :creator %>
            <div class="container"><%= form.text_field :creator %></div>
          </div>

        <div class="field">
          <%= form.label :image %>
          <div class="container"><%= form.file_field :image %></div>
        </div>

        <div class="actions btn">
            <%= form.submit %>
        </div>
    </div> 
<% end %>

app/views/products/admin_index.html.erb
<h1>All Artworks</h1>

<table>
  <thead>
    <tr>
      <th>Artwork Name</th>
      <th>Image</th>
      <th>Price</th>
      <th>Availability</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_title %></td>
        <td><% if product.image.attached? %>
        <%= link_to cl_image_tag(product.image.key, :width=>100, :crop=>"fit"), product %>
        <% end %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
         <%# link for user products %>
        <td><%= link_to product.user.username, userproducts_path(product.user_id) %></td> 


        <%# validates that only a signed in user can see or modify products %>
        <% if user_signed_in? %>
          <%# validates that only users who have created the product or admin can edit and destroy %>
          <% if product.can_change?(current_user) %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if product.quantity_zero? %>
              <td><%= 'This product is no longer available' %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/edit.html.erb
<h1>Editing Artwork for Sale</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%# Only shows products with 1 or more quantity %>
<h1>Artworks</h1>


<% @availableproducts.each do |product| %>
<div class="responsive">
  <div class="gallery">
    <% if product.image.attached? %>
        <%= link_to cl_image_tag(product.image.key, :width=>600, :height=>400), product %>
        <% end %>
    <div class="desc"><p><%= product.product_title %></p>
    <p>A$<%= product.price %></p>
    <p>Listed by <%= link_to product.user.username, userproducts_path(product.user_id) %></p>
    </div>
  </div>
</div>
    <% end %>
<div class="clearfix"></div>

app/views/products/new.html.erb
<h1>New Artwork for Sale</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%# validation for quantity, if quantity zero product show will not display %>  
<% if @product.quantity_zero? && !current_user.is_admin? %>
    <h2> Sorry, this artwork is not available! Click back to go back to homepage.</h2>
  <% else %>

<% if @product.quantity_zero? && current_user.is_admin? %>
<h2> This artwork is no longer available for sale.</h2>
<% end %>

<p>
  <strong>Artwork name:</strong>
  <%= @product.product_title %>
</p>

<p>
  <% if @product.image.attached? %>
  <%= cl_image_tag(@product.image.key) %>
  <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Medium:</strong>
  <%= @product.medium %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @product.creator %>
</p>

<p>
  <strong>Seller:</strong>
  <%# link for user products %>
  <%= link_to @product.user.username, userproducts_path(@product.user.id) %>
</p>


<%# form tag helper going to charges path %>
<%= form_tag charges_path do %>
  <article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
       <p><%= flash[:error] %></p>
    </div>
  <% end %>
  </article>

  <%# dont allow creator to purchase own items %>
  <% if @product.can_change?(current_user) %>
    <%#= link_to 'Purchase disabled: You cannot purchase your own items', products_path%> 
  <% else %>
    
    <%# code block for stripe payments added purchase lable %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description= "<%= @product.product_title %>"
            data-amount="<%= @product.price_in_cents %>"
            data-currency="aud"
            data-label="Purchase!" 
            data-locale="auto"></script>
  <% end %>
<% end %>

<%# validates only user who created product or admin can edit %>
  <% if @product.can_change?(current_user) %>
    <%= link_to 'Edit', edit_product_path(@product) %> |
  <% end %>
<% end %>
<%= link_to 'Back', products_path %> <br/>
<%= link_to 'Send message to seller', new_conversation_path(:r => @product.user.id) %>

app/views/products/userproducts.html.erb
<%# view for user products %>
<h1>My Artworks for Sale</h1>

<table>
  <thead>
    <tr>
      <th>Artwork Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price</th>
      <th>Medium</th>
      <th>Availability</th>
      <th>Creator</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userproducts.each do |product| %>
      <tr>
        <td><%= product.product_title %></td>
        <td><%= product.description %></td>
        <td>  <% if product.image.attached? %>
        <%= cl_image_tag(product.image.key, :width=>100, :crop=>"fit") %>
        <% end %></td>
        <td><%= product.price %></td>
        <td><%= product.medium %></td>
        <td><%= product.quantity %></td>
        <td><%= product.creator %></td>
        <td><%= product.user.username %></td> 

        <td><%= link_to 'Show', product %></td>
        <%# validates that only a signed in user can see or modify products %>
        <% if user_signed_in? %>
          <%# validates that only users who have created the product or admin can edit and destroy %>
          <% if product.can_change?(current_user) %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>