config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders
  resources :products, :charges

  # Resource routes for the messaging feature using mailboxer
  resources :conversations do
    resources :messages
  end

  devise_for :users

  # route for user products
  get 'products/userproducts/:user_id/' => 'products#userproducts', :as => :userproducts
  get 'products/admin_index/admin' => 'products#admin_index', :as => :admin_index
  get 'orders/myorders/:buyer_id' => 'orders#myorders', :as => :myorders
  get 'orders/mysales/:seller_id' => 'orders#mysales', :as => :mysales
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # route for delete conversation
  delete 'conversations/:id/' => 'conversations#destroy', :as => :conversation_destroy

  # Root path = products index
  root 'products#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kraftme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <style>
div.gallery {
    border: 1px solid #ccc;
}

div.gallery:hover {
    border: 1px solid #777;
}

div.gallery img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 15px;
    text-align: center;
}

* {
    box-sizing: border-box;
}

.responsive {
    padding: 0 6px;
    float: left;
    width: 24.99999%;
}

@media only screen and (max-width: 700px) {
    .responsive {
        width: 49.99999%;
        margin: 6px 0;
    }
}

@media only screen and (max-width: 500px) {
    .responsive {
        width: 100%;
    }
}

.clearfix:after {
    content: "";
    display: table;
    clear: both;
}
</style>

  </head>

  <body>
    <%# <p id="notice"><%= notice</p> %> 
    <p id="alert"><%= alert %></p>

<%# implemented a fixed nav bar %>
    <nav class="navbar nav-fixed-top navbar-inverse ">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand">KraftMe</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          
          <% if user_signed_in? %>
            <h4>Welcome <%= current_user.email %>!</h4> 
            <li><%= link_to 'Home', products_path %><li>
            <li><%= link_to 'Update Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sell Artwork', new_product_path %></li>
            <%# link for user products %>
            <li><%= link_to 'My Artworks for Sale', userproducts_path(current_user) %></li>
            <li><%= link_to 'My Purchases', myorders_path(current_user) %></li>
            <li><%= link_to 'My Fulfilled Sales', mysales_path(current_user) %></li>
            <%# link to current users message inbox %>
            <li><%= link_to 'My Messages' , conversations_path %></li>
            <% if current_user.is_admin? %>
              <li><%= link_to 'Admin - All Artworks', admin_index_path %></li>
              <li><%= link_to 'Admin - All Transactions', orders_path %></li>
            <% end %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <%= link_to 'Login or Sign Up!', new_user_session_path %>
            <% end %>
        </ul>
     </div>     
    </nav>

    <div class="jumbotron">
      <%= yield %>
    </div>

    

  </body>
</html>



  
    
    
      

   
  